apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
  ports:
    - name: data
      port: 1099
      targetPort: 1099
    - name: http
      port: 9999
      targetPort: 9999
    {{ if .Values.debug }}
    - name: debug
      port: 5005
      targetPort: 5005
    {{ end }}
  selector:
    name: {{ .Values.pod.name }}
